---
- name: Deploy Spring Boot
  hosts: app
  vars:
    ci_cd_namespace: erob-ci-cd
    dev_namespace: erob-dev
    demo_namespace: erob-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier